### ISSUE TITLE
Add pre-commit hooks for ipynb

### ISSUE THREAD

**Issue by lizzypokerface** [lizzypokerface/ipynb-proj-setup#1]
# Context

Add pre-commit hooks for ipynb

# References

Yes, there are pre-commit hooks specifically designed for Jupyter Notebook files. Pre-commit hooks can help maintain code quality and ensure consistency in Jupyter Notebooks. Here are some popular pre-commit hooks for Jupyter Notebook files:

1. **nbstripout**: This hook removes the output cells from Jupyter Notebooks, which helps reduce the size of the notebooks and avoid merge conflicts related to output data.
    ```yaml
    - repo: https://github.com/kynan/nbstripout
      rev: 0.3.9  # Use the latest tag or commit
      hooks:
        - id: nbstripout
    ```

2. **nbqa**: This hook allows running any standard Python code quality tool (like black, flake8, isort) on Jupyter Notebooks.
    ```yaml
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.2.2  # Use the latest tag or commit
      hooks:
        - id: nbqa-black
        - id: nbqa-flake8
        - id: nbqa-isort
    ```

3. **jupyter-notebook-linter**: This hook uses the `nbconvert` tool to convert notebooks to Python scripts and then runs linters (like flake8) on the converted scripts.
    ```yaml
    - repo: https://github.com/s-weigand/jupyter-notebook-linter
      rev: v0.1.0  # Use the latest tag or commit
      hooks:
        - id: jupyter-notebook-linter
    ```

4. **nbdime**: This is useful for diffing and merging Jupyter Notebooks, but it also includes pre-commit hooks for checking notebook content.
    ```yaml
    - repo: https://github.com/jupyter/nbdime
      rev: 3.1.1  # Use the latest tag or commit
      hooks:
        - id: nbdime
    ```

To set up these pre-commit hooks for Jupyter Notebook files, you can create or update your `.pre-commit-config.yaml` file with the desired hooks as shown in the examples above. Then, install the hooks by running:
```bash
pre-commit install
```

This setup will ensure that the specified checks and formatting rules are applied to your Jupyter Notebooks before they are committed to the repository.
